apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-consumer
  labels:
    app: message-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-consumer
  template:
    metadata:
      labels:
        app: message-consumer
    spec:
      containers:
        - name: message-consumer
          image: vklooney/message-consumer:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "192.168.64.105:9092"
